- name: cnd901
  description: Something isn't working
  color: d73a4a
- name: cnd903
  description: Improvements or additions to documentation
  color: 0075ca
- name: cnd904
  description: This issue or pull request already exists
  color: cfd3d7
